version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Raise pull requests for version updates
    # against the `master` branch
    target-branch: "master"
    # Labels on pull requests for version updates
    labels:
      - "dependencies"
      - "automated"
    # Specify version update preferences
    versioning-strategy: auto
    # Allow up to 10 open pull requests for dependencies
    open-pull-requests-limit: 10 